<?php

namespace WidgetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DoctrineORMUserRepository extends EntityRepository implements UserRepository
{
    public function findActiveUserByHash($userHash)
    {
        $user = $this->createQueryBuilder('u')
            ->where('u.hash = :userHash and u.is_active = true')
            ->setParameter('userHash', $userHash)
            ->getQuery()
            ->getOneOrNullResult();
        return $user;

    }

    public function isUserActive($userId)
    {
        return ;
    }
}
